# Generated by Django 3.2.9 on 2022-11-22 00:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/icons/12.png', upload_to=accounts.models.profiles_image_path),
        ),
    ]
