# Generated by Django 3.2.9 on 2022-11-22 01:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/icons/11.png', upload_to=accounts.models.profiles_image_path),
        ),
    ]
