# Generated by Django 3.2.9 on 2022-11-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('known_for_department', models.CharField(max_length=50)),
                ('popularity', models.FloatField()),
                ('profile_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('released_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('homepage', models.CharField(blank=True, max_length=100)),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('backdrop_path', models.CharField(blank=True, max_length=200)),
                ('budget', models.IntegerField()),
                ('video', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('click_count', models.IntegerField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('people', models.ManyToManyField(blank=True, to='movies.People')),
            ],
        ),
    ]
